### ISSUE TITLE
NIV Empty

### ISSUE THREAD

**Issue by atersakyan** [rsyi/pylift#1]
Hello,

I've setup my model via TransformedOutcome, then wanted to check all the NIV features. However, when I use NIV (dict, or plot) all the included features are empty. The rest of the steps work and I get plots further down the line, but the NIV being empty leads me to believe they are incorrect.

Setting up the model
```up = TransformedOutcome(df, col_treatment='Response', col_outcome='TotalRevenueFoodItems',random_state=4, stratify=y)```

Call NIV
```up.NIV_dict```

Output of NIV: see screenshot
<img width="745" alt="Screen Shot 2019-10-28 at 3 06 23 PM" src="https://user-images.githubusercontent.com/48836989/67725873-1f330900-f9a1-11e9-8a24-971253f39b3c.png">

Thank you.

**Comment by rsyi** [comment]
At the moment, NIV is only implemented for binary outcomes.
We'll work on implementing this feature!

**Comment by rsyi** [comment]
Just made the fix -- `pip install --upgrade pylift` to get the changes. Let me know if there are still any problems! :)
